package com.logistica.demo.presupuesto.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.logistica.demo.presupuesto.api.BudgetAvailability;
import com.logistica.demo.sharedkernel.domain.FiscalDimension;
import com.logistica.demo.sharedkernel.domain.Moneda;
import java.math.BigDecimal;
import java.time.Instant;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class BudgetAvailabilityJdbcAdapterTest {

    private JdbcTemplate jdbcTemplate;
    private BudgetAvailabilityJdbcAdapter adapter;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:budget-availability-" + System.nanoTime() + ";DB_CLOSE_DELAY=-1;NON_KEYWORDS=MONTH",
                "sa",
                "");
        jdbcTemplate = new JdbcTemplate(dataSource);
        createSchema();
        seedPim();
        adapter = new BudgetAvailabilityJdbcAdapter(jdbcTemplate);
    }

    @Test
    void shouldCalculateAvailabilityFromApprovedPimLine() {
        BudgetAvailability availability = adapter.findAvailability(dimension(), Moneda.PEN).orElseThrow();

        assertDecimalEquals("1000.00", availability.assigned().amount());
        assertDecimalEquals("200.00", availability.precommitted().amount());
        assertDecimalEquals("300.00", availability.committed().amount());
        assertDecimalEquals("500.00", availability.available().amount());
    }

    @Test
    void shouldIgnoreDraftPimAndMissingDimensions() {
        jdbcTemplate.update("UPDATE presupuesto.budget_exercises SET status = 'DRAFT', approved_at = NULL WHERE id = 1");

        assertTrue(adapter.findAvailability(dimension(), Moneda.PEN).isEmpty());
        assertTrue(adapter.findAvailability(new FiscalDimension(1L, 2026, 2, 10L, 20L, 30L, 40L), Moneda.PEN).isEmpty());
    }

    @Test
    void shouldFindStateWithPessimisticLockForBudgetOperations() {
        BudgetLineState state = adapter.findStateForUpdate(dimension(), Moneda.PEN).orElseThrow();

        assertEquals(10L, state.budgetLineId());
        assertDecimalEquals("500.00", state.availableAmount());
    }

    private FiscalDimension dimension() {
        return new FiscalDimension(1L, 2026, 1, 10L, 20L, 30L, 40L);
    }

    private void assertDecimalEquals(String expected, BigDecimal actual) {
        assertEquals(0, new BigDecimal(expected).compareTo(actual));
    }

    private void seedPim() {
        Instant now = Instant.parse("2026-01-01T00:00:00Z");
        jdbcTemplate.update(
                """
                INSERT INTO presupuesto.budget_exercises (
                    id, company_id, fiscal_year, exercise_type, status, approved_at,
                    created_by, created_at, updated_by, updated_at
                ) VALUES (1, 1, 2026, 'PIM', 'APPROVED', ?, 'system', ?, 'system', ?)
                """,
                now,
                now,
                now);
        jdbcTemplate.update(
                """
                INSERT INTO presupuesto.budget_lines (
                    id, budget_exercise_id, company_id, fiscal_year, month,
                    cost_center_id, financing_source_id, goal_id, expense_classifier_id,
                    currency_code, assigned_amount, precommitted_amount, committed_amount,
                    created_by, created_at, updated_by, updated_at
                ) VALUES (10, 1, 1, 2026, 1, 10, 20, 30, 40, 'PEN', 1000, 200, 300, 'system', ?, 'system', ?)
                """,
                now,
                now);
    }

    private void createSchema() {
        jdbcTemplate.execute("CREATE SCHEMA presupuesto");
        jdbcTemplate.execute("""
                CREATE TABLE presupuesto.budget_exercises(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id BIGINT NOT NULL,
                    fiscal_year SMALLINT NOT NULL,
                    exercise_type VARCHAR(20) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    approved_at TIMESTAMP WITH TIME ZONE,
                    created_by VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_by VARCHAR(100) NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE presupuesto.budget_lines(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    budget_exercise_id BIGINT NOT NULL,
                    company_id BIGINT NOT NULL,
                    fiscal_year SMALLINT NOT NULL,
                    month SMALLINT NOT NULL,
                    cost_center_id BIGINT NOT NULL,
                    financing_source_id BIGINT NOT NULL,
                    goal_id BIGINT NOT NULL,
                    expense_classifier_id BIGINT NOT NULL,
                    currency_code CHAR(3) NOT NULL,
                    assigned_amount NUMERIC(18,2) NOT NULL,
                    precommitted_amount NUMERIC(18,2) NOT NULL,
                    committed_amount NUMERIC(18,2) NOT NULL,
                    created_by VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_by VARCHAR(100) NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
                """);
    }
}
