logging.level.root=INFO
logging.level.com.logistica.demo=INFO
logging.structured.format.console=logstash

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

management.endpoint.health.show-details=never
