spring.application.name=logistica-demo

server.address=0.0.0.0
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:logistica_demo}}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=logistica_demo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/postgresql

spring.jackson.time-zone=America/Lima
spring.jackson.default-property-inclusion=non_null

logging.level.root=INFO
logging.level.com.logistica.demo=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

demo.finance.igv-rate=0.18
demo.finance.exchange-rate=3.35
demo.report.company-name=${DEMO_REPORT_COMPANY_NAME:Logistica Demo SAC}

demo.jwt.secret=${DEMO_JWT_SECRET}
demo.jwt.expiration-ms=${DEMO_JWT_EXPIRATION_MS:3600000}

demo.cors.allowed-origins=${DEMO_CORS_ALLOWED_ORIGINS:http://localhost:4200}
