CREATE SCHEMA presupuesto;

CREATE TABLE presupuesto.budget_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    exercise_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    approved_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_budget_exercise_company_year_type UNIQUE (company_id, fiscal_year, exercise_type),
    CONSTRAINT fk_budget_exercise_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT ck_budget_exercise_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_budget_exercise_type CHECK (exercise_type IN ('UNIDADES', 'PIA', 'PIM')),
    CONSTRAINT ck_budget_exercise_status CHECK (status IN ('DRAFT', 'APPROVED', 'CLOSED')),
    CONSTRAINT ck_budget_exercise_approval CHECK (
        (status = 'DRAFT' AND approved_at IS NULL AND closed_at IS NULL)
        OR (status = 'APPROVED' AND approved_at IS NOT NULL AND closed_at IS NULL)
        OR (status = 'CLOSED' AND approved_at IS NOT NULL AND closed_at IS NOT NULL)
    )
);

CREATE TABLE presupuesto.budget_ceilings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    cost_center_id BIGINT NOT NULL,
    financing_source_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    expense_classifier_id BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    ceiling_amount NUMERIC(18, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_budget_ceiling_dimension UNIQUE (
        company_id,
        fiscal_year,
        month,
        cost_center_id,
        financing_source_id,
        goal_id,
        expense_classifier_id,
        currency_code
    ),
    CONSTRAINT fk_budget_ceiling_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_budget_ceiling_cost_center FOREIGN KEY (cost_center_id)
        REFERENCES platform.cost_centers(id),
    CONSTRAINT fk_budget_ceiling_financing_source FOREIGN KEY (financing_source_id)
        REFERENCES platform.financing_sources(id),
    CONSTRAINT fk_budget_ceiling_goal FOREIGN KEY (goal_id)
        REFERENCES platform.goals(id),
    CONSTRAINT fk_budget_ceiling_classifier FOREIGN KEY (expense_classifier_id)
        REFERENCES platform.expense_classifiers(id),
    CONSTRAINT fk_budget_ceiling_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_budget_ceiling_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_budget_ceiling_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_budget_ceiling_amount CHECK (ceiling_amount >= 0)
);

CREATE TABLE presupuesto.budget_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_exercise_id BIGINT NOT NULL,
    budget_ceiling_id BIGINT,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    cost_center_id BIGINT NOT NULL,
    financing_source_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    expense_classifier_id BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    assigned_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    precommitted_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    committed_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_budget_line_dimension UNIQUE (
        budget_exercise_id,
        month,
        cost_center_id,
        financing_source_id,
        goal_id,
        expense_classifier_id,
        currency_code
    ),
    CONSTRAINT fk_budget_line_exercise FOREIGN KEY (budget_exercise_id)
        REFERENCES presupuesto.budget_exercises(id),
    CONSTRAINT fk_budget_line_ceiling FOREIGN KEY (budget_ceiling_id)
        REFERENCES presupuesto.budget_ceilings(id),
    CONSTRAINT fk_budget_line_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_budget_line_cost_center FOREIGN KEY (cost_center_id)
        REFERENCES platform.cost_centers(id),
    CONSTRAINT fk_budget_line_financing_source FOREIGN KEY (financing_source_id)
        REFERENCES platform.financing_sources(id),
    CONSTRAINT fk_budget_line_goal FOREIGN KEY (goal_id)
        REFERENCES platform.goals(id),
    CONSTRAINT fk_budget_line_classifier FOREIGN KEY (expense_classifier_id)
        REFERENCES platform.expense_classifiers(id),
    CONSTRAINT fk_budget_line_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_budget_line_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_budget_line_amounts CHECK (
        assigned_amount >= 0
        AND precommitted_amount >= 0
        AND committed_amount >= 0
        AND assigned_amount >= precommitted_amount + committed_amount
    )
);

CREATE TABLE presupuesto.budget_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_line_id BIGINT NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    source_module VARCHAR(40) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    source_number VARCHAR(80) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    idempotency_key VARCHAR(120),
    actor VARCHAR(100) NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_budget_movement_line FOREIGN KEY (budget_line_id)
        REFERENCES presupuesto.budget_lines(id),
    CONSTRAINT fk_budget_movement_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_budget_movement_type CHECK (
        movement_type IN (
            'ASSIGNMENT',
            'PRECOMMITMENT',
            'PRECOMMITMENT_RELEASE',
            'COMMITMENT',
            'COMMITMENT_RELEASE'
        )
    ),
    CONSTRAINT ck_budget_movement_amount CHECK (amount > 0),
    CONSTRAINT ck_budget_movement_source_not_blank CHECK (
        BTRIM(source_module) <> ''
        AND BTRIM(source_type) <> ''
        AND BTRIM(source_number) <> ''
        AND BTRIM(actor) <> ''
    )
);

CREATE UNIQUE INDEX uk_budget_movement_idempotency
    ON presupuesto.budget_movements(budget_line_id, movement_type, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX ix_budget_exercises_company_year_status
    ON presupuesto.budget_exercises(company_id, fiscal_year, status);
CREATE INDEX ix_budget_ceilings_dimension_active
    ON presupuesto.budget_ceilings(
        company_id,
        fiscal_year,
        month,
        cost_center_id,
        financing_source_id,
        goal_id,
        expense_classifier_id,
        active
    );
CREATE INDEX ix_budget_lines_availability
    ON presupuesto.budget_lines(
        company_id,
        fiscal_year,
        month,
        cost_center_id,
        financing_source_id,
        goal_id,
        expense_classifier_id
    );
CREATE INDEX ix_budget_movements_source
    ON presupuesto.budget_movements(source_module, source_type, source_id);
