CREATE TABLE presupuesto.budget_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consolidation_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    unit_budget_exercise_id BIGINT NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    transferred_lines INTEGER NOT NULL,
    actor VARCHAR(100) NOT NULL,
    transferred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_budget_transfer_consolidation UNIQUE (consolidation_id),
    CONSTRAINT uk_budget_transfer_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_budget_transfer_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_budget_transfer_exercise FOREIGN KEY (unit_budget_exercise_id)
        REFERENCES presupuesto.budget_exercises(id),
    CONSTRAINT ck_budget_transfer_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_budget_transfer_lines CHECK (transferred_lines > 0),
    CONSTRAINT ck_budget_transfer_actor_not_blank CHECK (BTRIM(actor) <> '')
);

CREATE TABLE presupuesto.budget_transfer_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT NOT NULL,
    budget_line_id BIGINT NOT NULL,
    needs_plan_id BIGINT NOT NULL,
    needs_line_id BIGINT NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    approved_quantity NUMERIC(18, 4) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    CONSTRAINT uk_budget_transfer_line UNIQUE (transfer_id, needs_line_id, month),
    CONSTRAINT fk_budget_transfer_line_transfer FOREIGN KEY (transfer_id)
        REFERENCES presupuesto.budget_transfers(id),
    CONSTRAINT fk_budget_transfer_line_budget_line FOREIGN KEY (budget_line_id)
        REFERENCES presupuesto.budget_lines(id),
    CONSTRAINT fk_budget_transfer_line_item FOREIGN KEY (catalog_item_id)
        REFERENCES platform.catalog_items(id),
    CONSTRAINT ck_budget_transfer_line_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_budget_transfer_line_amounts CHECK (approved_quantity >= 0 AND amount >= 0)
);

CREATE INDEX ix_budget_transfer_lines_needs
    ON presupuesto.budget_transfer_lines(needs_plan_id, needs_line_id);
CREATE INDEX ix_budget_transfer_lines_budget_line
    ON presupuesto.budget_transfer_lines(budget_line_id);
