CREATE TABLE presupuesto.budget_plan_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pia_exercise_id BIGINT NOT NULL,
    reviewer VARCHAR(100) NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes VARCHAR(500),
    CONSTRAINT uk_budget_plan_review_exercise UNIQUE (pia_exercise_id),
    CONSTRAINT fk_budget_plan_review_exercise FOREIGN KEY (pia_exercise_id)
        REFERENCES presupuesto.budget_exercises(id),
    CONSTRAINT ck_budget_plan_review_reviewer CHECK (BTRIM(reviewer) <> '')
);

CREATE INDEX ix_budget_plan_reviews_reviewed_at
    ON presupuesto.budget_plan_reviews(reviewed_at);
