CREATE TABLE presupuesto.budget_controls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_module VARCHAR(40) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    source_number VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    actor VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_budget_control_status CHECK (status IN ('PRECOMMITTED', 'COMMITTED', 'RELEASED', 'REJECTED')),
    CONSTRAINT ck_budget_control_source_not_blank CHECK (
        BTRIM(source_module) <> ''
        AND BTRIM(source_type) <> ''
        AND BTRIM(source_number) <> ''
        AND BTRIM(actor) <> ''
    )
);

CREATE TABLE presupuesto.budget_control_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_control_id BIGINT NOT NULL,
    budget_line_id BIGINT NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    precommitted_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    committed_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    released_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uk_budget_control_line UNIQUE (budget_control_id, budget_line_id),
    CONSTRAINT fk_budget_control_line_control FOREIGN KEY (budget_control_id)
        REFERENCES presupuesto.budget_controls(id),
    CONSTRAINT fk_budget_control_line_budget_line FOREIGN KEY (budget_line_id)
        REFERENCES presupuesto.budget_lines(id),
    CONSTRAINT fk_budget_control_line_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_budget_control_line_amounts CHECK (
        amount > 0
        AND precommitted_amount >= 0
        AND committed_amount >= 0
        AND released_amount >= 0
        AND precommitted_amount + committed_amount + released_amount <= amount
    )
);

CREATE UNIQUE INDEX uk_budget_control_active_precommit
    ON presupuesto.budget_controls(source_module, source_type, source_id)
    WHERE status = 'PRECOMMITTED';

CREATE INDEX ix_budget_controls_source
    ON presupuesto.budget_controls(source_module, source_type, source_id);
CREATE INDEX ix_budget_control_lines_budget_line
    ON presupuesto.budget_control_lines(budget_line_id);
