CREATE SCHEMA logistica;

CREATE TABLE logistica.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(180) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_supplier_code UNIQUE (company_id, code),
    CONSTRAINT uk_logistics_supplier_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_supplier_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT ck_logistics_supplier_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_supplier_not_blank CHECK (BTRIM(code) <> '' AND BTRIM(name) <> '')
);

CREATE TABLE logistica.warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(180) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_warehouse_code UNIQUE (company_id, code),
    CONSTRAINT uk_logistics_warehouse_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_warehouse_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT ck_logistics_warehouse_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_warehouse_not_blank CHECK (BTRIM(code) <> '' AND BTRIM(name) <> '')
);

CREATE TABLE logistica.requisitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    number VARCHAR(40) NOT NULL,
    description VARCHAR(500) NOT NULL,
    supplier_id BIGINT,
    currency_code CHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    budget_control_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_requisition_number UNIQUE (company_id, fiscal_year, number),
    CONSTRAINT uk_logistics_requisition_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_requisition_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_logistics_requisition_supplier FOREIGN KEY (supplier_id)
        REFERENCES logistica.suppliers(id),
    CONSTRAINT fk_logistics_requisition_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_logistics_requisition_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_logistics_requisition_status CHECK (
        status IN ('DRAFT', 'SUBMITTED', 'OBSERVED', 'APPROVED', 'REJECTED', 'PRECOMMITTED', 'CANCELLED', 'LEGACY_IMPORTED')
    ),
    CONSTRAINT ck_logistics_requisition_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_requisition_not_blank CHECK (BTRIM(number) <> '' AND BTRIM(description) <> '')
);

CREATE TABLE logistica.requisition_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    needs_plan_id BIGINT,
    needs_line_id BIGINT,
    monthly_need_id BIGINT,
    catalog_item_id BIGINT NOT NULL,
    warehouse_id BIGINT,
    requested_quantity NUMERIC(18, 4) NOT NULL,
    approved_quantity NUMERIC(18, 4) NOT NULL DEFAULT 0,
    unit_price_estimated NUMERIC(18, 4) NOT NULL,
    subtotal_estimated NUMERIC(18, 2) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_requisition_line_number UNIQUE (requisition_id, line_number),
    CONSTRAINT uk_logistics_requisition_line_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_requisition_line_requisition FOREIGN KEY (requisition_id)
        REFERENCES logistica.requisitions(id),
    CONSTRAINT fk_logistics_requisition_line_item FOREIGN KEY (catalog_item_id)
        REFERENCES platform.catalog_items(id),
    CONSTRAINT fk_logistics_requisition_line_warehouse FOREIGN KEY (warehouse_id)
        REFERENCES logistica.warehouses(id),
    CONSTRAINT ck_logistics_requisition_line_quantities CHECK (
        requested_quantity > 0
        AND approved_quantity >= 0
        AND approved_quantity <= requested_quantity
        AND unit_price_estimated >= 0
        AND subtotal_estimated >= 0
    ),
    CONSTRAINT ck_logistics_requisition_line_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.requisition_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id BIGINT NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    comment VARCHAR(500),
    actor VARCHAR(100) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_req_status_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_req_status_requisition FOREIGN KEY (requisition_id)
        REFERENCES logistica.requisitions(id),
    CONSTRAINT ck_logistics_req_status_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_req_status_actor CHECK (BTRIM(actor) <> '')
);

CREATE TABLE logistica.approval_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    comment VARCHAR(500),
    actor VARCHAR(100) NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_approval_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_approval_requisition FOREIGN KEY (requisition_id)
        REFERENCES logistica.requisitions(id),
    CONSTRAINT ck_logistics_approval_action CHECK (action IN ('APPROVE', 'OBSERVE', 'REJECT')),
    CONSTRAINT ck_logistics_approval_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_approval_actor CHECK (BTRIM(actor) <> '')
);

CREATE TABLE logistica.quotation_processes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_quotation_process_requisition UNIQUE (requisition_id),
    CONSTRAINT uk_logistics_quotation_process_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_quotation_process_requisition FOREIGN KEY (requisition_id)
        REFERENCES logistica.requisitions(id),
    CONSTRAINT ck_logistics_quotation_process_status CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_logistics_quotation_process_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.supplier_quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_process_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    submitted_at TIMESTAMPTZ,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_supplier_quote UNIQUE (quotation_process_id, supplier_id),
    CONSTRAINT uk_logistics_supplier_quote_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_supplier_quote_process FOREIGN KEY (quotation_process_id)
        REFERENCES logistica.quotation_processes(id),
    CONSTRAINT fk_logistics_supplier_quote_supplier FOREIGN KEY (supplier_id)
        REFERENCES logistica.suppliers(id),
    CONSTRAINT fk_logistics_supplier_quote_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_logistics_supplier_quote_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'DISQUALIFIED', 'AWARDED')),
    CONSTRAINT ck_logistics_supplier_quote_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.supplier_quotation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_quotation_id BIGINT NOT NULL,
    requisition_line_id BIGINT NOT NULL,
    offered_quantity NUMERIC(18, 4) NOT NULL,
    unit_price NUMERIC(18, 4) NOT NULL,
    subtotal NUMERIC(18, 2) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_supplier_quote_line UNIQUE (supplier_quotation_id, requisition_line_id),
    CONSTRAINT uk_logistics_supplier_quote_line_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_supplier_quote_line_quote FOREIGN KEY (supplier_quotation_id)
        REFERENCES logistica.supplier_quotations(id),
    CONSTRAINT fk_logistics_supplier_quote_line_req_line FOREIGN KEY (requisition_line_id)
        REFERENCES logistica.requisition_lines(id),
    CONSTRAINT ck_logistics_supplier_quote_line_amounts CHECK (offered_quantity > 0 AND unit_price >= 0 AND subtotal >= 0),
    CONSTRAINT ck_logistics_supplier_quote_line_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.awards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_process_id BIGINT NOT NULL,
    supplier_quotation_id BIGINT NOT NULL,
    awarded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor VARCHAR(100) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_award_process UNIQUE (quotation_process_id),
    CONSTRAINT uk_logistics_award_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_award_process FOREIGN KEY (quotation_process_id)
        REFERENCES logistica.quotation_processes(id),
    CONSTRAINT fk_logistics_award_quote FOREIGN KEY (supplier_quotation_id)
        REFERENCES logistica.supplier_quotations(id),
    CONSTRAINT ck_logistics_award_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_award_actor CHECK (BTRIM(actor) <> '')
);

CREATE TABLE logistica.purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    number VARCHAR(40) NOT NULL,
    requisition_id BIGINT NOT NULL,
    award_id BIGINT,
    supplier_id BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    exchange_rate NUMERIC(18, 4) NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL,
    subtotal NUMERIC(18, 2) NOT NULL,
    tax_amount NUMERIC(18, 2) NOT NULL,
    total NUMERIC(18, 2) NOT NULL,
    budget_control_id BIGINT,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_purchase_order_number UNIQUE (company_id, fiscal_year, number),
    CONSTRAINT uk_logistics_purchase_order_requisition UNIQUE (requisition_id),
    CONSTRAINT uk_logistics_purchase_order_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_purchase_order_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_logistics_purchase_order_requisition FOREIGN KEY (requisition_id)
        REFERENCES logistica.requisitions(id),
    CONSTRAINT fk_logistics_purchase_order_award FOREIGN KEY (award_id)
        REFERENCES logistica.awards(id),
    CONSTRAINT fk_logistics_purchase_order_supplier FOREIGN KEY (supplier_id)
        REFERENCES logistica.suppliers(id),
    CONSTRAINT fk_logistics_purchase_order_currency FOREIGN KEY (currency_code)
        REFERENCES platform.currencies(code),
    CONSTRAINT ck_logistics_purchase_order_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_logistics_purchase_order_status CHECK (status IN ('DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', 'LEGACY_IMPORTED')),
    CONSTRAINT ck_logistics_purchase_order_amounts CHECK (exchange_rate > 0 AND subtotal >= 0 AND tax_amount >= 0 AND total >= 0),
    CONSTRAINT ck_logistics_purchase_order_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.purchase_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    requisition_line_id BIGINT,
    line_number INTEGER NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    warehouse_id BIGINT,
    ordered_quantity NUMERIC(18, 4) NOT NULL,
    received_quantity NUMERIC(18, 4) NOT NULL DEFAULT 0,
    unit_price NUMERIC(18, 4) NOT NULL,
    subtotal NUMERIC(18, 2) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_purchase_order_line_number UNIQUE (purchase_order_id, line_number),
    CONSTRAINT uk_logistics_purchase_order_line_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_purchase_order_line_order FOREIGN KEY (purchase_order_id)
        REFERENCES logistica.purchase_orders(id),
    CONSTRAINT fk_logistics_purchase_order_line_req_line FOREIGN KEY (requisition_line_id)
        REFERENCES logistica.requisition_lines(id),
    CONSTRAINT fk_logistics_purchase_order_line_item FOREIGN KEY (catalog_item_id)
        REFERENCES platform.catalog_items(id),
    CONSTRAINT fk_logistics_purchase_order_line_warehouse FOREIGN KEY (warehouse_id)
        REFERENCES logistica.warehouses(id),
    CONSTRAINT ck_logistics_purchase_order_line_amounts CHECK (
        ordered_quantity > 0
        AND received_quantity >= 0
        AND received_quantity <= ordered_quantity
        AND unit_price >= 0
        AND subtotal >= 0
    ),
    CONSTRAINT ck_logistics_purchase_order_line_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.purchase_order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    comment VARCHAR(500),
    actor VARCHAR(100) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_po_status_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_po_status_order FOREIGN KEY (purchase_order_id)
        REFERENCES logistica.purchase_orders(id),
    CONSTRAINT ck_logistics_po_status_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_po_status_actor CHECK (BTRIM(actor) <> '')
);

CREATE TABLE logistica.warehouse_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    number VARCHAR(40) NOT NULL,
    purchase_order_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor VARCHAR(100) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_logistics_warehouse_receipt_number UNIQUE (company_id, number),
    CONSTRAINT uk_logistics_warehouse_receipt_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_warehouse_receipt_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_logistics_warehouse_receipt_order FOREIGN KEY (purchase_order_id)
        REFERENCES logistica.purchase_orders(id),
    CONSTRAINT ck_logistics_warehouse_receipt_status CHECK (status IN ('REGISTERED', 'REVERSED')),
    CONSTRAINT ck_logistics_warehouse_receipt_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_warehouse_receipt_actor CHECK (BTRIM(actor) <> '')
);

CREATE TABLE logistica.warehouse_receipt_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_receipt_id BIGINT NOT NULL,
    purchase_order_line_id BIGINT NOT NULL,
    received_quantity NUMERIC(18, 4) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_warehouse_receipt_line UNIQUE (warehouse_receipt_id, purchase_order_line_id),
    CONSTRAINT uk_logistics_warehouse_receipt_line_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_warehouse_receipt_line_receipt FOREIGN KEY (warehouse_receipt_id)
        REFERENCES logistica.warehouse_receipts(id),
    CONSTRAINT fk_logistics_warehouse_receipt_line_order_line FOREIGN KEY (purchase_order_line_id)
        REFERENCES logistica.purchase_order_lines(id),
    CONSTRAINT ck_logistics_warehouse_receipt_line_quantity CHECK (received_quantity > 0),
    CONSTRAINT ck_logistics_warehouse_receipt_line_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

CREATE TABLE logistica.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    source_module VARCHAR(40) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    source_number VARCHAR(80) NOT NULL,
    actor VARCHAR(100) NOT NULL,
    moved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_inventory_movement_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_inventory_movement_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_logistics_inventory_movement_warehouse FOREIGN KEY (warehouse_id)
        REFERENCES logistica.warehouses(id),
    CONSTRAINT ck_logistics_inventory_movement_type CHECK (movement_type IN ('INBOUND', 'OUTBOUND', 'REVERSAL')),
    CONSTRAINT ck_logistics_inventory_movement_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO')),
    CONSTRAINT ck_logistics_inventory_movement_not_blank CHECK (
        BTRIM(source_module) <> ''
        AND BTRIM(source_type) <> ''
        AND BTRIM(source_number) <> ''
        AND BTRIM(actor) <> ''
    )
);

CREATE TABLE logistica.inventory_movement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_movement_id BIGINT NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    quantity NUMERIC(18, 4) NOT NULL,
    source_system VARCHAR(40) NOT NULL DEFAULT 'MVP1',
    legacy_id BIGINT,
    CONSTRAINT uk_logistics_inventory_movement_line_legacy UNIQUE (source_system, legacy_id),
    CONSTRAINT fk_logistics_inventory_movement_line_movement FOREIGN KEY (inventory_movement_id)
        REFERENCES logistica.inventory_movements(id),
    CONSTRAINT fk_logistics_inventory_movement_line_item FOREIGN KEY (catalog_item_id)
        REFERENCES platform.catalog_items(id),
    CONSTRAINT ck_logistics_inventory_movement_line_quantity CHECK (quantity > 0),
    CONSTRAINT ck_logistics_inventory_movement_line_source CHECK (source_system IN ('MVP1', 'LEGACY_DEMO'))
);

INSERT INTO logistica.suppliers (
    company_id, code, name, active, source_system, legacy_id,
    created_by, created_at, updated_by, updated_at
)
SELECT c.id, legacy.code, legacy.name, legacy.active, 'LEGACY_DEMO', legacy.id,
       legacy.created_by, legacy.created_at, legacy.updated_by, legacy.updated_at
FROM logistica_demo.proveedores legacy
JOIN platform.companies c ON c.code = 'DEMO';

INSERT INTO logistica.warehouses (
    company_id, code, name, active, source_system, legacy_id,
    created_by, created_at, updated_by, updated_at
)
SELECT c.id, legacy.code, legacy.name, legacy.active, 'LEGACY_DEMO', legacy.id,
       legacy.created_by, legacy.created_at, legacy.updated_by, legacy.updated_at
FROM logistica_demo.almacenes legacy
JOIN platform.companies c ON c.code = 'DEMO';

INSERT INTO logistica.requisitions (
    company_id, fiscal_year, number, description, supplier_id, currency_code,
    status, source_system, legacy_id, created_by, created_at, updated_by, updated_at
)
SELECT c.id,
       EXTRACT(YEAR FROM legacy.created_at)::SMALLINT,
       COALESCE(legacy.numero, 'LEGACY-REQ-' || legacy.id::TEXT),
       legacy.descripcion,
       supplier.id,
       SUBSTRING(legacy.moneda FROM 1 FOR 3),
       'LEGACY_IMPORTED',
       'LEGACY_DEMO',
       legacy.id,
       legacy.created_by,
       legacy.created_at,
       legacy.updated_by,
       legacy.updated_at
FROM logistica_demo.requerimientos legacy
JOIN platform.companies c ON c.code = 'DEMO'
JOIN logistica.suppliers supplier
  ON supplier.source_system = 'LEGACY_DEMO'
 AND supplier.legacy_id = legacy.proveedor_id;

INSERT INTO logistica.requisition_lines (
    requisition_id, line_number, catalog_item_id, warehouse_id,
    requested_quantity, approved_quantity, unit_price_estimated, subtotal_estimated,
    source_system, legacy_id
)
SELECT requisition.id,
       ROW_NUMBER() OVER (PARTITION BY legacy.requerimiento_id ORDER BY legacy.id),
       catalog_item.id,
       warehouse.id,
       legacy.cantidad,
       legacy.cantidad,
       legacy.precio_unitario_estimado,
       legacy.subtotal_linea,
       'LEGACY_DEMO',
       legacy.id
FROM logistica_demo.requerimiento_detalles legacy
JOIN logistica.requisitions requisition
  ON requisition.source_system = 'LEGACY_DEMO'
 AND requisition.legacy_id = legacy.requerimiento_id
JOIN logistica_demo.items legacy_item ON legacy_item.id = legacy.item_id
JOIN platform.catalog_items catalog_item
  ON catalog_item.company_id = requisition.company_id
 AND catalog_item.code = legacy_item.code
JOIN logistica.warehouses warehouse
  ON warehouse.source_system = 'LEGACY_DEMO'
 AND warehouse.legacy_id = legacy.almacen_id;

INSERT INTO logistica.requisition_status_history (
    requisition_id, previous_status, new_status, comment, actor, changed_at,
    source_system, legacy_id
)
SELECT requisition.id,
       legacy.estado_anterior,
       legacy.estado_nuevo,
       legacy.comentario,
       legacy.created_by,
       legacy.created_at,
       'LEGACY_DEMO',
       legacy.id
FROM logistica_demo.requerimiento_estado_historial legacy
JOIN logistica.requisitions requisition
  ON requisition.source_system = 'LEGACY_DEMO'
 AND requisition.legacy_id = legacy.requerimiento_id;

INSERT INTO logistica.approval_records (
    requisition_id, action, comment, actor, decided_at, source_system, legacy_id
)
SELECT requisition.id,
       CASE legacy.accion
           WHEN 'APROBAR' THEN 'APPROVE'
           WHEN 'OBSERVAR' THEN 'OBSERVE'
           WHEN 'RECHAZAR' THEN 'REJECT'
           ELSE 'OBSERVE'
       END,
       legacy.comentario,
       legacy.created_by,
       legacy.decision_at,
       'LEGACY_DEMO',
       legacy.id
FROM logistica_demo.aprobaciones legacy
JOIN logistica.requisitions requisition
  ON requisition.source_system = 'LEGACY_DEMO'
 AND requisition.legacy_id = legacy.requerimiento_id;

INSERT INTO logistica.purchase_orders (
    company_id, fiscal_year, number, requisition_id, supplier_id, currency_code,
    exchange_rate, status, subtotal, tax_amount, total,
    source_system, legacy_id, issued_at, created_by, created_at, updated_by, updated_at
)
SELECT requisition.company_id,
       EXTRACT(YEAR FROM legacy.generated_at)::SMALLINT,
       COALESCE(legacy.numero, 'LEGACY-OC-' || legacy.id::TEXT),
       requisition.id,
       supplier.id,
       legacy.moneda,
       legacy.tipo_cambio,
       'LEGACY_IMPORTED',
       legacy.subtotal,
       legacy.igv,
       legacy.total,
       'LEGACY_DEMO',
       legacy.id,
       legacy.generated_at,
       legacy.created_by,
       legacy.created_at,
       legacy.updated_by,
       legacy.updated_at
FROM logistica_demo.ordenes_compra legacy
JOIN logistica.requisitions requisition
  ON requisition.source_system = 'LEGACY_DEMO'
 AND requisition.legacy_id = legacy.requerimiento_id
JOIN logistica.suppliers supplier
  ON supplier.source_system = 'LEGACY_DEMO'
 AND supplier.legacy_id = legacy.proveedor_id;

INSERT INTO logistica.purchase_order_lines (
    purchase_order_id, requisition_line_id, line_number, catalog_item_id, warehouse_id,
    ordered_quantity, unit_price, subtotal, source_system, legacy_id
)
SELECT purchase_order.id,
       requisition_line.id,
       ROW_NUMBER() OVER (PARTITION BY legacy.orden_compra_id ORDER BY legacy.id),
       catalog_item.id,
       warehouse.id,
       legacy.cantidad,
       legacy.precio_unitario,
       legacy.subtotal_linea,
       'LEGACY_DEMO',
       legacy.id
FROM logistica_demo.orden_compra_detalles legacy
JOIN logistica.purchase_orders purchase_order
  ON purchase_order.source_system = 'LEGACY_DEMO'
 AND purchase_order.legacy_id = legacy.orden_compra_id
JOIN logistica_demo.items legacy_item ON legacy_item.id = legacy.item_id
JOIN platform.catalog_items catalog_item
  ON catalog_item.company_id = purchase_order.company_id
 AND catalog_item.code = legacy_item.code
JOIN logistica.warehouses warehouse
  ON warehouse.source_system = 'LEGACY_DEMO'
 AND warehouse.legacy_id = legacy.almacen_id
LEFT JOIN logistica.requisition_lines requisition_line
  ON requisition_line.requisition_id = purchase_order.requisition_id
 AND requisition_line.catalog_item_id = catalog_item.id
 AND requisition_line.warehouse_id = warehouse.id;

CREATE INDEX ix_logistics_requisitions_company_status
    ON logistica.requisitions(company_id, status, created_at DESC);
CREATE INDEX ix_logistics_requisitions_source
    ON logistica.requisitions(source_system, legacy_id);
CREATE INDEX ix_logistics_requisition_lines_needs
    ON logistica.requisition_lines(needs_line_id, monthly_need_id);
CREATE INDEX ix_logistics_purchase_orders_company_status
    ON logistica.purchase_orders(company_id, status, issued_at DESC);
CREATE INDEX ix_logistics_purchase_orders_source
    ON logistica.purchase_orders(source_system, legacy_id);
CREATE INDEX ix_logistics_inventory_movements_source
    ON logistica.inventory_movements(source_module, source_type, source_id);

DO $$
DECLARE
    legacy_suppliers_count INTEGER;
    migrated_suppliers_count INTEGER;
    legacy_warehouses_count INTEGER;
    migrated_warehouses_count INTEGER;
    legacy_requisitions_count INTEGER;
    migrated_requisitions_count INTEGER;
    legacy_requisition_lines_count INTEGER;
    migrated_requisition_lines_count INTEGER;
    legacy_purchase_orders_count INTEGER;
    migrated_purchase_orders_count INTEGER;
    unresolved_requisition_lines_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO legacy_suppliers_count FROM logistica_demo.proveedores;
    SELECT COUNT(*) INTO migrated_suppliers_count FROM logistica.suppliers WHERE source_system = 'LEGACY_DEMO';
    SELECT COUNT(*) INTO legacy_warehouses_count FROM logistica_demo.almacenes;
    SELECT COUNT(*) INTO migrated_warehouses_count FROM logistica.warehouses WHERE source_system = 'LEGACY_DEMO';
    SELECT COUNT(*) INTO legacy_requisitions_count FROM logistica_demo.requerimientos;
    SELECT COUNT(*) INTO migrated_requisitions_count FROM logistica.requisitions WHERE source_system = 'LEGACY_DEMO';
    SELECT COUNT(*) INTO legacy_requisition_lines_count FROM logistica_demo.requerimiento_detalles;
    SELECT COUNT(*) INTO migrated_requisition_lines_count FROM logistica.requisition_lines WHERE source_system = 'LEGACY_DEMO';
    SELECT COUNT(*) INTO legacy_purchase_orders_count FROM logistica_demo.ordenes_compra;
    SELECT COUNT(*) INTO migrated_purchase_orders_count FROM logistica.purchase_orders WHERE source_system = 'LEGACY_DEMO';
    SELECT COUNT(*) INTO unresolved_requisition_lines_count
    FROM logistica.requisition_lines
    WHERE source_system = 'LEGACY_DEMO'
      AND (catalog_item_id IS NULL OR warehouse_id IS NULL);

    IF migrated_suppliers_count <> legacy_suppliers_count THEN
        RAISE EXCEPTION 'LOG-T02 validation failed: migrated suppliers %, expected %',
            migrated_suppliers_count, legacy_suppliers_count;
    END IF;
    IF migrated_warehouses_count <> legacy_warehouses_count THEN
        RAISE EXCEPTION 'LOG-T02 validation failed: migrated warehouses %, expected %',
            migrated_warehouses_count, legacy_warehouses_count;
    END IF;
    IF migrated_requisitions_count <> legacy_requisitions_count THEN
        RAISE EXCEPTION 'LOG-T02 validation failed: migrated requisitions %, expected %',
            migrated_requisitions_count, legacy_requisitions_count;
    END IF;
    IF migrated_requisition_lines_count <> legacy_requisition_lines_count THEN
        RAISE EXCEPTION 'LOG-T02 validation failed: migrated requisition lines %, expected %',
            migrated_requisition_lines_count, legacy_requisition_lines_count;
    END IF;
    IF migrated_purchase_orders_count <> legacy_purchase_orders_count THEN
        RAISE EXCEPTION 'LOG-T02 validation failed: migrated purchase orders %, expected %',
            migrated_purchase_orders_count, legacy_purchase_orders_count;
    END IF;
    IF unresolved_requisition_lines_count <> 0 THEN
        RAISE EXCEPTION 'LOG-T02 validation failed: % legacy requisition lines without item or warehouse',
            unresolved_requisition_lines_count;
    END IF;
END $$;
