CREATE SCHEMA platform;

CREATE TABLE platform.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    legal_name VARCHAR(200) NOT NULL,
    trade_name VARCHAR(200),
    tax_id VARCHAR(20),
    timezone VARCHAR(50) NOT NULL DEFAULT 'America/Lima',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_company_code UNIQUE (code),
    CONSTRAINT uk_company_tax_id UNIQUE (tax_id),
    CONSTRAINT ck_company_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_company_legal_name_not_blank CHECK (BTRIM(legal_name) <> '')
);

CREATE TABLE platform.organization_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    parent_id BIGINT,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    unit_type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_organization_unit_company_code UNIQUE (company_id, code),
    CONSTRAINT uk_organization_unit_company_id UNIQUE (company_id, id),
    CONSTRAINT fk_organization_unit_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_organization_unit_parent FOREIGN KEY (company_id, parent_id)
        REFERENCES platform.organization_units(company_id, id),
    CONSTRAINT ck_organization_unit_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_organization_unit_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_organization_unit_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE TABLE platform.cost_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    valid_from DATE,
    valid_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cost_center_company_code UNIQUE (company_id, code),
    CONSTRAINT uk_cost_center_company_id UNIQUE (company_id, id),
    CONSTRAINT fk_cost_center_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_cost_center_organization_unit FOREIGN KEY (company_id, organization_unit_id)
        REFERENCES platform.organization_units(company_id, id),
    CONSTRAINT ck_cost_center_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_cost_center_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_cost_center_validity CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE platform.financing_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_financing_source_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_financing_source_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_financing_source_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_financing_source_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE platform.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_goal_company_year_code UNIQUE (company_id, fiscal_year, code),
    CONSTRAINT fk_goal_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_goal_fiscal_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_goal_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_goal_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE platform.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_activity_company_year_code UNIQUE (company_id, fiscal_year, code),
    CONSTRAINT fk_activity_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_activity_fiscal_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_activity_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_activity_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE platform.expense_classifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_expense_classifier_company_code UNIQUE (company_id, code),
    CONSTRAINT uk_expense_classifier_company_id UNIQUE (company_id, id),
    CONSTRAINT fk_expense_classifier_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_expense_classifier_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_expense_classifier_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE platform.currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(3) NOT NULL,
    name VARCHAR(80) NOT NULL,
    symbol VARCHAR(8) NOT NULL,
    decimal_places SMALLINT NOT NULL DEFAULT 2,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_currency_code UNIQUE (code),
    CONSTRAINT ck_currency_code_upper CHECK (code = UPPER(code)),
    CONSTRAINT ck_currency_decimal_places CHECK (decimal_places BETWEEN 0 AND 4)
);

CREATE TABLE platform.units_of_measure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_unit_of_measure_code UNIQUE (code),
    CONSTRAINT ck_unit_of_measure_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_unit_of_measure_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE platform.catalog_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    unit_of_measure_id BIGINT NOT NULL,
    expense_classifier_id BIGINT,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    item_type VARCHAR(20) NOT NULL DEFAULT 'GOOD',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_catalog_item_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_catalog_item_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT fk_catalog_item_unit FOREIGN KEY (unit_of_measure_id) REFERENCES platform.units_of_measure(id),
    CONSTRAINT fk_catalog_item_classifier FOREIGN KEY (company_id, expense_classifier_id)
        REFERENCES platform.expense_classifiers(company_id, id),
    CONSTRAINT ck_catalog_item_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_catalog_item_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_catalog_item_type CHECK (item_type IN ('GOOD', 'SERVICE'))
);

CREATE TABLE platform.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(160),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT ck_user_username_not_blank CHECK (BTRIM(username) <> ''),
    CONSTRAINT ck_user_password_hash_not_blank CHECK (BTRIM(password_hash) <> '')
);

CREATE TABLE platform.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    system_role BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_code UNIQUE (code),
    CONSTRAINT ck_role_code_not_blank CHECK (BTRIM(code) <> '')
);

CREATE TABLE platform.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(160) NOT NULL,
    module VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_permission_code UNIQUE (code),
    CONSTRAINT ck_permission_code_not_blank CHECK (BTRIM(code) <> '')
);

CREATE TABLE platform.role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES platform.roles(id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES platform.permissions(id)
);

CREATE TABLE platform.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_role_company UNIQUE (user_id, role_id, company_id),
    CONSTRAINT uk_user_role_company_id UNIQUE (company_id, id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES platform.users(id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES platform.roles(id),
    CONSTRAINT fk_user_role_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_user_role_validity CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE platform.user_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    organization_unit_id BIGINT,
    cost_center_id BIGINT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_scope_user_role FOREIGN KEY (company_id, user_role_id)
        REFERENCES platform.user_roles(company_id, id),
    CONSTRAINT fk_user_scope_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT fk_user_scope_organization_unit FOREIGN KEY (company_id, organization_unit_id)
        REFERENCES platform.organization_units(company_id, id),
    CONSTRAINT fk_user_scope_cost_center FOREIGN KEY (company_id, cost_center_id)
        REFERENCES platform.cost_centers(company_id, id),
    CONSTRAINT uk_user_scope UNIQUE NULLS NOT DISTINCT
        (user_role_id, company_id, organization_unit_id, cost_center_id)
);

CREATE TABLE platform.refresh_tokens (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    replaced_by UUID,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES platform.users(id),
    CONSTRAINT fk_refresh_token_replacement FOREIGN KEY (replaced_by) REFERENCES platform.refresh_tokens(id),
    CONSTRAINT ck_refresh_token_expiration CHECK (expires_at > issued_at),
    CONSTRAINT ck_refresh_token_revocation CHECK (revoked_at IS NULL OR revoked_at >= issued_at)
);

CREATE TABLE platform.fiscal_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fiscal_period_company_year_month UNIQUE (company_id, fiscal_year, month),
    CONSTRAINT fk_fiscal_period_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_fiscal_period_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_fiscal_period_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_fiscal_period_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_fiscal_period_dates CHECK (ends_on >= starts_on)
);

CREATE TABLE platform.document_sequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    prefix VARCHAR(20) NOT NULL,
    current_value BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_document_sequence UNIQUE (company_id, fiscal_year, document_type),
    CONSTRAINT fk_document_sequence_company FOREIGN KEY (company_id) REFERENCES platform.companies(id),
    CONSTRAINT ck_document_sequence_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_document_sequence_value CHECK (current_value >= 0)
);

CREATE TABLE platform.audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    actor VARCHAR(100) NOT NULL,
    effective_role VARCHAR(50),
    action VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(64),
    trace_id VARCHAR(128),
    changes JSONB,
    CONSTRAINT fk_audit_event_company FOREIGN KEY (company_id) REFERENCES platform.companies(id)
);

CREATE TABLE platform.outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(160) NOT NULL,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000),
    CONSTRAINT ck_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_outbox_publication CHECK (published_at IS NULL OR published_at >= occurred_at)
);

CREATE TABLE platform.idempotency_keys (
    id UUID PRIMARY KEY,
    scope VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_status INTEGER,
    response_content_type VARCHAR(100),
    response_body JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_idempotency_scope_key UNIQUE (scope, idempotency_key),
    CONSTRAINT ck_idempotency_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_idempotency_response_status CHECK (
        response_status IS NULL OR response_status BETWEEN 100 AND 599
    ),
    CONSTRAINT ck_idempotency_expiration CHECK (expires_at > created_at)
);

CREATE INDEX ix_organization_units_company_active
    ON platform.organization_units(company_id, active);
CREATE INDEX ix_cost_centers_company_active
    ON platform.cost_centers(company_id, active);
CREATE INDEX ix_financing_sources_company_active
    ON platform.financing_sources(company_id, active);
CREATE INDEX ix_goals_company_year_active
    ON platform.goals(company_id, fiscal_year, active);
CREATE INDEX ix_activities_company_year_active
    ON platform.activities(company_id, fiscal_year, active);
CREATE INDEX ix_expense_classifiers_company_active
    ON platform.expense_classifiers(company_id, active);
CREATE INDEX ix_catalog_items_company_active
    ON platform.catalog_items(company_id, active);
CREATE INDEX ix_user_roles_user_active
    ON platform.user_roles(user_id, active);
CREATE INDEX ix_user_scopes_user_role
    ON platform.user_scopes(user_role_id);
CREATE INDEX ix_refresh_tokens_user_active
    ON platform.refresh_tokens(user_id, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX ix_audit_events_aggregate
    ON platform.audit_events(aggregate_type, aggregate_id, occurred_at DESC);
CREATE INDEX ix_audit_events_trace
    ON platform.audit_events(trace_id) WHERE trace_id IS NOT NULL;
CREATE INDEX ix_outbox_events_pending
    ON platform.outbox_events(occurred_at) WHERE published_at IS NULL;
CREATE INDEX ix_idempotency_keys_expiration
    ON platform.idempotency_keys(expires_at);
