CREATE SCHEMA cuadronecesidades;

CREATE TABLE cuadronecesidades.needs_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    cost_center_id BIGINT NOT NULL,
    financing_source_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    title VARCHAR(200) NOT NULL,
    submitted_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    consolidated_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_needs_plan_dimension UNIQUE (company_id, fiscal_year, cost_center_id, financing_source_id, goal_id),
    CONSTRAINT fk_needs_plan_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT fk_needs_plan_cost_center FOREIGN KEY (company_id, cost_center_id)
        REFERENCES platform.cost_centers(company_id, id),
    CONSTRAINT fk_needs_plan_financing_source FOREIGN KEY (financing_source_id)
        REFERENCES platform.financing_sources(id),
    CONSTRAINT fk_needs_plan_goal FOREIGN KEY (goal_id)
        REFERENCES platform.goals(id),
    CONSTRAINT ck_needs_plan_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_needs_plan_title_not_blank CHECK (BTRIM(title) <> ''),
    CONSTRAINT ck_needs_plan_status CHECK (
        status IN ('DRAFT', 'SUBMITTED', 'OBSERVED', 'REVIEWED', 'REJECTED', 'CONSOLIDATED', 'TRANSFERRED')
    ),
    CONSTRAINT ck_needs_plan_review_order CHECK (
        reviewed_at IS NULL OR submitted_at IS NULL OR reviewed_at >= submitted_at
    ),
    CONSTRAINT ck_needs_plan_consolidation_order CHECK (
        consolidated_at IS NULL OR reviewed_at IS NULL OR consolidated_at >= reviewed_at
    )
);

CREATE TABLE cuadronecesidades.need_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    needs_plan_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    expense_classifier_id BIGINT NOT NULL,
    unit_of_measure_id BIGINT NOT NULL,
    item_code VARCHAR(40) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    unit_code VARCHAR(20) NOT NULL,
    requested_quantity NUMERIC(18, 4) NOT NULL,
    reviewed_quantity NUMERIC(18, 4),
    approved_quantity NUMERIC(18, 4),
    estimated_unit_price NUMERIC(18, 2) NOT NULL,
    estimated_total NUMERIC(18, 2) NOT NULL,
    consumed_quantity NUMERIC(18, 4) NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_need_line_number UNIQUE (needs_plan_id, line_number),
    CONSTRAINT fk_need_line_plan FOREIGN KEY (needs_plan_id)
        REFERENCES cuadronecesidades.needs_plans(id),
    CONSTRAINT fk_need_line_catalog_item FOREIGN KEY (catalog_item_id)
        REFERENCES platform.catalog_items(id),
    CONSTRAINT fk_need_line_classifier FOREIGN KEY (company_id, expense_classifier_id)
        REFERENCES platform.expense_classifiers(company_id, id),
    CONSTRAINT fk_need_line_unit FOREIGN KEY (unit_of_measure_id)
        REFERENCES platform.units_of_measure(id),
    CONSTRAINT ck_need_line_number_positive CHECK (line_number > 0),
    CONSTRAINT ck_need_line_item_code_not_blank CHECK (BTRIM(item_code) <> ''),
    CONSTRAINT ck_need_line_item_name_not_blank CHECK (BTRIM(item_name) <> ''),
    CONSTRAINT ck_need_line_unit_code_not_blank CHECK (BTRIM(unit_code) <> ''),
    CONSTRAINT ck_need_line_quantities CHECK (
        requested_quantity > 0
        AND (reviewed_quantity IS NULL OR reviewed_quantity >= 0)
        AND (approved_quantity IS NULL OR approved_quantity >= 0)
        AND consumed_quantity >= 0
        AND consumed_quantity <= COALESCE(approved_quantity, requested_quantity)
    ),
    CONSTRAINT ck_need_line_amounts CHECK (
        estimated_unit_price >= 0 AND estimated_total >= 0
    )
);

CREATE TABLE cuadronecesidades.monthly_needs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    need_line_id BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    requested_quantity NUMERIC(18, 4) NOT NULL,
    reviewed_quantity NUMERIC(18, 4),
    approved_quantity NUMERIC(18, 4),
    consumed_quantity NUMERIC(18, 4) NOT NULL DEFAULT 0,
    CONSTRAINT uk_monthly_need_line_month UNIQUE (need_line_id, month),
    CONSTRAINT fk_monthly_need_line FOREIGN KEY (need_line_id)
        REFERENCES cuadronecesidades.need_lines(id),
    CONSTRAINT ck_monthly_need_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_monthly_need_quantities CHECK (
        requested_quantity >= 0
        AND (reviewed_quantity IS NULL OR reviewed_quantity >= 0)
        AND (approved_quantity IS NULL OR approved_quantity >= 0)
        AND consumed_quantity >= 0
        AND consumed_quantity <= COALESCE(approved_quantity, requested_quantity)
    )
);

CREATE INDEX ix_needs_plans_company_year_status
    ON cuadronecesidades.needs_plans(company_id, fiscal_year, status);
CREATE INDEX ix_needs_plans_cost_center
    ON cuadronecesidades.needs_plans(company_id, cost_center_id, fiscal_year);
CREATE INDEX ix_need_lines_item
    ON cuadronecesidades.need_lines(company_id, catalog_item_id);
CREATE INDEX ix_need_lines_classifier
    ON cuadronecesidades.need_lines(company_id, expense_classifier_id);
CREATE INDEX ix_monthly_needs_line
    ON cuadronecesidades.monthly_needs(need_line_id, month);
