CREATE TABLE cuadronecesidades.needs_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    window_type VARCHAR(30) NOT NULL,
    opens_at TIMESTAMPTZ NOT NULL,
    closes_at TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_needs_window UNIQUE (company_id, fiscal_year, window_type),
    CONSTRAINT fk_needs_window_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT ck_needs_window_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_needs_window_type CHECK (window_type IN ('REGISTRATION', 'REVIEW', 'CONSOLIDATION')),
    CONSTRAINT ck_needs_window_dates CHECK (closes_at > opens_at)
);

CREATE INDEX ix_needs_windows_company_year_active
    ON cuadronecesidades.needs_windows(company_id, fiscal_year, active);
