CREATE TABLE cuadronecesidades.needs_consolidations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    consolidated_at TIMESTAMPTZ NOT NULL,
    reversed_at TIMESTAMPTZ,
    transferred_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_needs_consolidation_company FOREIGN KEY (company_id)
        REFERENCES platform.companies(id),
    CONSTRAINT ck_needs_consolidation_year CHECK (fiscal_year BETWEEN 2000 AND 2200),
    CONSTRAINT ck_needs_consolidation_status CHECK (status IN ('CONSOLIDATED', 'REVERSED', 'TRANSFERRED')),
    CONSTRAINT ck_needs_consolidation_reversal CHECK (reversed_at IS NULL OR status = 'REVERSED'),
    CONSTRAINT ck_needs_consolidation_transfer CHECK (transferred_at IS NULL OR status = 'TRANSFERRED')
);

CREATE TABLE cuadronecesidades.needs_consolidation_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consolidation_id BIGINT NOT NULL,
    needs_plan_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    cost_center_id BIGINT NOT NULL,
    financing_source_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    CONSTRAINT uk_needs_consolidation_source UNIQUE (consolidation_id, needs_plan_id),
    CONSTRAINT fk_needs_consolidation_source_header FOREIGN KEY (consolidation_id)
        REFERENCES cuadronecesidades.needs_consolidations(id),
    CONSTRAINT fk_needs_consolidation_source_plan FOREIGN KEY (needs_plan_id)
        REFERENCES cuadronecesidades.needs_plans(id)
);

CREATE TABLE cuadronecesidades.needs_consolidation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consolidation_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    cost_center_id BIGINT NOT NULL,
    financing_source_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    expense_classifier_id BIGINT NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    unit_of_measure_id BIGINT NOT NULL,
    item_code VARCHAR(40) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    unit_code VARCHAR(20) NOT NULL,
    approved_quantity NUMERIC(18, 4) NOT NULL,
    estimated_total NUMERIC(18, 2) NOT NULL,
    CONSTRAINT uk_needs_consolidation_line UNIQUE (
        consolidation_id,
        cost_center_id,
        financing_source_id,
        goal_id,
        expense_classifier_id,
        catalog_item_id
    ),
    CONSTRAINT fk_needs_consolidation_line_header FOREIGN KEY (consolidation_id)
        REFERENCES cuadronecesidades.needs_consolidations(id),
    CONSTRAINT fk_needs_consolidation_line_item FOREIGN KEY (catalog_item_id)
        REFERENCES platform.catalog_items(id),
    CONSTRAINT ck_needs_consolidation_line_item_code_not_blank CHECK (BTRIM(item_code) <> ''),
    CONSTRAINT ck_needs_consolidation_line_item_name_not_blank CHECK (BTRIM(item_name) <> ''),
    CONSTRAINT ck_needs_consolidation_line_unit_code_not_blank CHECK (BTRIM(unit_code) <> ''),
    CONSTRAINT ck_needs_consolidation_line_amounts CHECK (approved_quantity >= 0 AND estimated_total >= 0)
);

CREATE UNIQUE INDEX uk_needs_consolidation_open
    ON cuadronecesidades.needs_consolidations(company_id, fiscal_year)
    WHERE status IN ('CONSOLIDATED', 'TRANSFERRED');

CREATE INDEX ix_needs_consolidation_sources_plan
    ON cuadronecesidades.needs_consolidation_sources(needs_plan_id);
CREATE INDEX ix_needs_consolidation_lines_dimension
    ON cuadronecesidades.needs_consolidation_lines(
        company_id,
        fiscal_year,
        cost_center_id,
        financing_source_id,
        goal_id,
        expense_classifier_id
    );
