CREATE SCHEMA IF NOT EXISTS platform;

CREATE TABLE platform.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    legal_name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE platform.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE
);

CREATE TABLE platform.user_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    organization_unit_id BIGINT,
    cost_center_id BIGINT
);

CREATE TABLE platform.refresh_tokens (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by UUID
);

CREATE TABLE platform.organization_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    parent_id BIGINT,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    unit_type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL,
    valid_from DATE,
    valid_to DATE
);

CREATE TABLE platform.cost_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    organization_unit_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    valid_from DATE,
    valid_to DATE,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.financing_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.expense_classifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(3) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    symbol VARCHAR(8) NOT NULL,
    decimal_places SMALLINT NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.units_of_measure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.catalog_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    unit_of_measure_id BIGINT NOT NULL,
    expense_classifier_id BIGINT,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(200) NOT NULL,
    item_type VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.fiscal_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fiscal_period_company_year_month UNIQUE (company_id, fiscal_year, month)
);

CREATE TABLE platform.document_sequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    fiscal_year SMALLINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    prefix VARCHAR(20) NOT NULL,
    current_value BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_document_sequence UNIQUE (company_id, fiscal_year, document_type)
);

CREATE TABLE platform.audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    actor VARCHAR(100) NOT NULL,
    effective_role VARCHAR(50),
    action VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address VARCHAR(64),
    trace_id VARCHAR(128),
    changes CLOB
);

CREATE TABLE platform.outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(160) NOT NULL,
    payload CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000)
);

CREATE TABLE platform.idempotency_keys (
    id UUID PRIMARY KEY,
    scope VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_status INTEGER,
    response_content_type VARCHAR(100),
    response_body CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_idempotency_scope_key UNIQUE (scope, idempotency_key)
);

INSERT INTO logistica_demo.usuarios (
    username, password, full_name, role, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('solicitante', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Solicitante Demo', 'SOLICITANTE', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('aprobador', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Aprobador Demo', 'APROBADOR', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('compras', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Compras Demo', 'COMPRAS', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('admin', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Administrador Demo', 'ADMIN', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO logistica_demo.proveedores (
    code, name, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('PRV-001', 'Proveedor Andino SAC', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('PRV-002', 'Servicios Logisticos del Peru', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO logistica_demo.almacenes (
    code, name, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('ALM-001', 'Almacen Central', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ALM-002', 'Almacen Norte', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO logistica_demo.items (
    code, name, unit_measure, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('ITM-001', 'Mesa operativa', 'UND', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ITM-002', 'Silla ergonomica', 'UND', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ITM-003', 'Archivador metalico', 'UND', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO platform.companies (code, legal_name, active)
VALUES ('DEMO', 'Logistica Demo SAC', TRUE);

INSERT INTO platform.roles (code, active) VALUES
    ('SOLICITANTE', TRUE),
    ('APROBADOR', TRUE),
    ('COMPRAS', TRUE),
    ('ADMIN', TRUE);

INSERT INTO platform.permissions (code, active) VALUES
    ('PLATFORM.MASTER.READ', TRUE),
    ('PLATFORM.MASTER.WRITE', TRUE),
    ('PLATFORM.SECURITY.WRITE', TRUE),
    ('LOGISTICA.REQUISITION.WRITE', TRUE),
    ('LOGISTICA.REQUISITION.APPROVE', TRUE),
    ('LOGISTICA.PURCHASE.WRITE', TRUE);

INSERT INTO platform.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM platform.roles r
JOIN platform.permissions p ON
       r.code = 'ADMIN'
    OR (r.code = 'SOLICITANTE' AND p.code IN ('PLATFORM.MASTER.READ', 'LOGISTICA.REQUISITION.WRITE'))
    OR (r.code = 'APROBADOR' AND p.code IN ('PLATFORM.MASTER.READ', 'LOGISTICA.REQUISITION.APPROVE'))
    OR (r.code = 'COMPRAS' AND p.code IN ('PLATFORM.MASTER.READ', 'LOGISTICA.PURCHASE.WRITE'));

INSERT INTO platform.users (username, password_hash, full_name, active)
SELECT
    username,
    '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK',
    full_name,
    active
FROM logistica_demo.usuarios;

INSERT INTO platform.user_roles (user_id, role_id, company_id, active, valid_from)
SELECT u.id, r.id, c.id, TRUE, CURRENT_TIMESTAMP
FROM platform.users u
JOIN logistica_demo.usuarios legacy_user ON legacy_user.username = u.username
JOIN platform.roles r ON r.code = legacy_user.role
CROSS JOIN platform.companies c
WHERE c.code = 'DEMO';

INSERT INTO platform.user_scopes (user_role_id, company_id)
SELECT id, company_id FROM platform.user_roles;

INSERT INTO platform.organization_units (company_id, parent_id, code, name, unit_type, active)
VALUES
    (1, NULL, 'GER-GRAL', 'Gerencia General', 'MANAGEMENT', TRUE),
    (1, 1, 'ADM', 'Administracion y Finanzas', 'ADMINISTRATION', TRUE),
    (1, 1, 'LOG', 'Logistica y Abastecimiento', 'OPERATIONS', TRUE);

INSERT INTO platform.cost_centers (company_id, organization_unit_id, code, name, valid_from, active)
VALUES
    (1, 2, 'CC-ADM', 'Centro de costo Administracion', DATE '2026-01-01', TRUE),
    (1, 3, 'CC-LOG', 'Centro de costo Logistica', DATE '2026-01-01', TRUE);

INSERT INTO platform.financing_sources (company_id, code, name, active)
VALUES
    (1, 'RO', 'Recursos ordinarios', TRUE),
    (1, 'RDR', 'Recursos directamente recaudados', TRUE);

INSERT INTO platform.goals (company_id, fiscal_year, code, name, active)
VALUES
    (1, 2026, 'META-001', 'Gestion administrativa institucional', TRUE),
    (1, 2026, 'META-002', 'Abastecimiento oportuno de bienes y servicios', TRUE);

INSERT INTO platform.activities (company_id, fiscal_year, code, name, active)
VALUES
    (1, 2026, 'ACT-001', 'Operacion administrativa', TRUE),
    (1, 2026, 'ACT-002', 'Gestion de compras y almacenes', TRUE);

INSERT INTO platform.expense_classifiers (company_id, code, name, active)
VALUES
    (1, '2.3.1.5.1.2', 'Papeleria en general, utiles y materiales de oficina', TRUE),
    (1, '2.3.2.7.11.99', 'Servicios diversos', TRUE),
    (1, '2.6.3.2.1.2', 'Mobiliario y equipos de oficina', TRUE);

INSERT INTO platform.currencies (code, name, symbol, decimal_places, active)
VALUES
    ('PEN', 'Sol peruano', 'S/', 2, TRUE),
    ('USD', 'Dolar estadounidense', '$', 2, TRUE);

INSERT INTO platform.units_of_measure (code, name, active)
VALUES
    ('UND', 'Unidad', TRUE),
    ('CAJA', 'Caja', TRUE),
    ('PAQ', 'Paquete', TRUE),
    ('GLB', 'Global', TRUE),
    ('MTR', 'Metro', TRUE),
    ('LTR', 'Litro', TRUE),
    ('SERV', 'Servicio', TRUE);

INSERT INTO platform.catalog_items (
    company_id, unit_of_measure_id, expense_classifier_id, code, name, item_type, active
)
SELECT
    1,
    uom.id,
    classifier.id,
    legacy_item.code,
    legacy_item.name,
    'GOOD',
    legacy_item.active
FROM logistica_demo.items legacy_item
CROSS JOIN platform.units_of_measure uom
CROSS JOIN platform.expense_classifiers classifier
WHERE uom.code = 'UND'
  AND classifier.code = '2.6.3.2.1.2';

INSERT INTO platform.catalog_items (
    company_id, unit_of_measure_id, expense_classifier_id, code, name, item_type, active
)
SELECT 1, uom.id, classifier.id, seed.code, seed.name, seed.item_type, TRUE
FROM (
    VALUES
        ('ITM-004', 'Papel bond A4 75g', 'GOOD', 'CAJA', '2.3.1.5.1.2'),
        ('ITM-005', 'Archivadores de palanca tamano oficio', 'GOOD', 'PAQ', '2.3.1.5.1.2'),
        ('ITM-006', 'Toner para impresora laser', 'GOOD', 'UND', '2.3.1.5.1.2'),
        ('ITM-007', 'Cable de red categoria 6', 'GOOD', 'MTR', '2.3.1.5.1.2'),
        ('ITM-008', 'Alcohol liquido para limpieza', 'GOOD', 'LTR', '2.3.1.5.1.2'),
        ('SERV-001', 'Mantenimiento preventivo de mobiliario', 'SERVICE', 'SERV', '2.3.2.7.11.99'),
        ('SERV-002', 'Servicio de transporte local', 'SERVICE', 'GLB', '2.3.2.7.11.99')
) AS seed(code, name, item_type, unit_code, classifier_code)
JOIN platform.units_of_measure uom ON uom.code = seed.unit_code
JOIN platform.expense_classifiers classifier ON classifier.code = seed.classifier_code;
