CREATE SCHEMA IF NOT EXISTS platform;

CREATE TABLE platform.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    legal_name VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL
);

CREATE TABLE platform.role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE platform.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE
);

CREATE TABLE platform.user_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    organization_unit_id BIGINT,
    cost_center_id BIGINT
);

CREATE TABLE platform.refresh_tokens (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by UUID
);

INSERT INTO logistica_demo.usuarios (
    username, password, full_name, role, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('solicitante', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Solicitante Demo', 'SOLICITANTE', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('aprobador', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Aprobador Demo', 'APROBADOR', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('compras', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Compras Demo', 'COMPRAS', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('admin', '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK', 'Administrador Demo', 'ADMIN', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO logistica_demo.proveedores (
    code, name, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('PRV-001', 'Proveedor Andino SAC', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('PRV-002', 'Servicios Logisticos del Peru', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO logistica_demo.almacenes (
    code, name, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('ALM-001', 'Almacen Central', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ALM-002', 'Almacen Norte', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO logistica_demo.items (
    code, name, unit_measure, active, created_by, created_at, updated_by, updated_at
) VALUES
    ('ITM-001', 'Mesa operativa', 'UND', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ITM-002', 'Silla ergonomica', 'UND', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
    ('ITM-003', 'Archivador metalico', 'UND', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);

INSERT INTO platform.companies (code, legal_name, active)
VALUES ('DEMO', 'Logistica Demo SAC', TRUE);

INSERT INTO platform.roles (code, active) VALUES
    ('SOLICITANTE', TRUE),
    ('APROBADOR', TRUE),
    ('COMPRAS', TRUE),
    ('ADMIN', TRUE);

INSERT INTO platform.permissions (code, active) VALUES
    ('PLATFORM.MASTER.READ', TRUE),
    ('PLATFORM.MASTER.WRITE', TRUE),
    ('PLATFORM.SECURITY.WRITE', TRUE),
    ('LOGISTICA.REQUISITION.WRITE', TRUE),
    ('LOGISTICA.REQUISITION.APPROVE', TRUE),
    ('LOGISTICA.PURCHASE.WRITE', TRUE);

INSERT INTO platform.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM platform.roles r
JOIN platform.permissions p ON
       r.code = 'ADMIN'
    OR (r.code = 'SOLICITANTE' AND p.code IN ('PLATFORM.MASTER.READ', 'LOGISTICA.REQUISITION.WRITE'))
    OR (r.code = 'APROBADOR' AND p.code IN ('PLATFORM.MASTER.READ', 'LOGISTICA.REQUISITION.APPROVE'))
    OR (r.code = 'COMPRAS' AND p.code IN ('PLATFORM.MASTER.READ', 'LOGISTICA.PURCHASE.WRITE'));

INSERT INTO platform.users (username, password_hash, full_name, active)
SELECT
    username,
    '$2a$12$QOAwHgrBpS/bbsdZSr.6heedCQi03lEPAMvUeirYvjP/wkmMeR1pK',
    full_name,
    active
FROM logistica_demo.usuarios;

INSERT INTO platform.user_roles (user_id, role_id, company_id, active, valid_from)
SELECT u.id, r.id, c.id, TRUE, CURRENT_TIMESTAMP
FROM platform.users u
JOIN logistica_demo.usuarios legacy_user ON legacy_user.username = u.username
JOIN platform.roles r ON r.code = legacy_user.role
CROSS JOIN platform.companies c
WHERE c.code = 'DEMO';

INSERT INTO platform.user_scopes (user_role_id, company_id)
SELECT id, company_id FROM platform.user_roles;
